---
- name: Configuração de serviços Ngnix
  hosts: all
  become: true

  tasks:
    - name: Install Nginx
      apt:    
        cache_valid_time: 86400
        pkg:
          - nginx

    - name: Enable Nginx
      ansible.builtin.systemd:
        name: nginx
        enabled: True

    - name: Configure index.html
      template:
        src: template.j2
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Restart ninx
      ansible.builtin.systemd:
        name: nginx
        state: restarted  