---
- name: 'Criação de instancia, grupo de segurança e inclusão no grupo'
  hosts: localhost
  connection: local
  gather_facts: False
  remote_user: ubuntu
  vars:
    keypair: Par_de_chaves # Nome da chave criada na console da AWS
    region: us-east-1
    instance_type: t2.micro
    image:
      id: ami-0557a15b87f6559cf
    count: 2
  tasks:
     - name: 'Criar segurança de grupo'
       ec2_group:
          name: web_services
          description: Allow SSH and HTTP access
          region: "{{ region }}"
          rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
       register: ec2_group

     - name: 'Lançar instâncias'
       ec2_instance:
        key_name: "{{ keypair }}"
        region: "{{ region }}"       
        image: "{{ image }}"         
        instance_type: "{{ instance_type }}"
        count: "{{ count }}"      
        security_group: "{{ec2_group.group_id}}"  
        wait: true
        network:
          assing_public_ip: true
       register: ec2

     - name: 'Saida de informações das instâncias'
       debug:
        var: ec2